name: Mirror Pantheon -> GitHub

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Local branch to push to Pantheon (e.g. main or your-feature-branch)'
        required: true
        default: 'master'

env:
  PANTHEON_GIT_URL: ${{ secrets.PANTHEON_GIT_URL }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Start ssh-agent and add PANTHEON key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PANTHEON_SSH_KEY }}

      - name: Add Pantheon host key to known_hosts (extract host/port from URL)
        run: |
          set -e
          mkdir -p ~/.ssh
          URL="${PANTHEON_GIT_URL}"
          # strip protocol and user
          NO_PROTO="${URL#ssh://}"
          NO_PROTO="${NO_PROTO#git@}"
          NO_USER="${NO_PROTO#*@}"
          # host[:port] before the first slash
          HOSTPORT="${NO_USER%%/*}"
          HOST="${HOSTPORT%%:*}"
          PORT="${HOSTPORT#*:}"
          if [ "$PORT" != "$HOSTPORT" ]; then
            ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts 2>/dev/null || ssh-keyscan "$HOST" >> ~/.ssh/known_hosts
          else
            ssh-keyscan "$HOST" >> ~/.ssh/known_hosts
          fi

      - name: Mirror clone Pantheon repository
        env:
          PANTHEON_GIT_URL: ${{ secrets.PANTHEON_GIT_URL }}
        run: |
          rm -rf pantheon.git
          git clone --mirror "${PANTHEON_GIT_URL}" pantheon.git

      - name: Push branches and tags to GitHub (safe: no deletions)
        env:
          GH_REPO: ${{ github.repository }}
        run: |
          cd pantheon.git
          # Use GITHUB_TOKEN to push to GitHub over HTTPS (no extra auth setup needed)
          git remote set-url --push origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GH_REPO}.git"

          # Push each local branch explicitly (creates/updates remote branches; does NOT delete remote branches)
          git for-each-ref --format='%(refname:short)' refs/heads | \
            while read -r BR; do
              echo "Pushing branch: $BR"
              git push origin "refs/heads/$BR:refs/heads/$BR" || {
                echo "Failed to push branch $BR"
                exit 1
              }
            done

          # Push tags
          git push origin --tags